config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "routes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :routes, only: %i[index new create show results] do
    resources :runs, only: %i[create] do
    get '/running', to: 'runs#running', as: :running
    end
  end

  get '/results', to: 'routes#results', as: :results
  patch '/end_run/:id', to: 'runs#end_run', as: :end_run
  resources :runs, only: %i[edit update show] do
    get '/running', to: 'runs#running', as: :running
    resources :bookmarks, only: %i[create update]
  end
  get "style", to: "pages#style"
  get "runs/:id/summary", to: "runs#summary", as: :summary

  resources :bookmarks, only: %i[index]
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  has_many_attached :photos

  belongs_to :user
  belongs_to :route

  validates :user, uniqueness: { scope: :route,
    message: "sorry, already in your bookmark" }
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = current_user.bookmarks.order(created_at: :desc)
  end

  def create
    @route = Run.find(params[:run_id]).route
    @bookmark = Bookmark.find_by(user: current_user, route: @route)
    if @bookmark.nil?
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.user = current_user
      @bookmark.route = @route
             if @bookmark.save
          redirect_to bookmarks_path, notice: 'Bookmark created successfuly.'
        else
          render :new, status: :unprocessable_entity

      end
    else
      if params[:bookmark][:photos].present?
        @bookmark.photos.attach(params[:bookmark][:photos])
        redirect_to bookmarks_path, notice: 'Photo attached to existing bookmark.'
      end
    end
  end

  def update
    @route = Run.find(params[:run_id]).route
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update!(bookmark_params)
    if params[:bookmark][:photos].present?
      @bookmark.photos.attach(params[:bookmark][:photos])
    end
    redirect_to bookmarks_path
  end

  private

  def bookmark_params
    params.fetch(:bookmark, {}).permit(:comment, photos: [])
  end
end

app/views/bookmarks/index.html.erb
<h1>Saved routes</h1>
  <div class="my-4">
  <% @bookmarks.each do |bookmark| %>
      <div class="card-run my-3">
        <% if bookmark.photos.attached? %>
        <%= cl_image_tag bookmark.photos.first.key, width: 124, height: 124, crop: :fill, class: "image-card" %>
          <% else %>
        <%= image_tag "map.png",  width: 124, crop: :fill, class: "image-card" %>
          <% end %>
        <div class="card-run-infos">
          <%# Suggestion: wrap link_to around entire card to make it clickable (with do end syntax) %>
          <h2><%= link_to bookmark.route.name, run_path(bookmark.route.runs.last) %></h2>

          <div class="card-text-icon ">
            <i class="fa-solid fa-person-running"></i>
            <p><strong>Distance:</strong> <%= bookmark.route.distance %> km</p>
          </div>
          <p><%= bookmark.route.description %></p>
        </div>
      </div>
  <% end %>
</div>