config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "routes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :routes, only: %i[index new create show results] do
    resources :runs, only: %i[create] do
    get '/running', to: 'runs#running', as: :running
    end
  end

  get '/results', to: 'routes#results', as: :results
  patch '/end_run/:id', to: 'runs#end_run', as: :end_run
  resources :runs, only: %i[edit update show] do
    get '/running', to: 'runs#running', as: :running
    resources :bookmarks, only: %i[create update]
  end
  get "style", to: "pages#style"
  get "runs/:id/summary", to: "runs#summary", as: :summary

  resources :bookmarks, only: %i[index]
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :user
  belongs_to :route
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  #def new
    #@run = Run.new
    #@route = Route.find(params[:route_id])
  #end

  def create
    @route = Route.find(params[:route_id])
    @run = Run.new
    @run.route = @route
    @run.user = current_user
    @run.starting_time = Time.now
    @run.save!
    redirect_to run_running_path(@run)
  end

  def running
    @run = Run.find(params[:run_id])
    @route = @run.route
    @bookmark = Bookmark.find_by(user: current_user, route: @run.route) || Bookmark.new
  end

  def show
    @run = Run.find(params[:id])
    @bookmark = Bookmark.find_by(user: current_user, route: @run.route)
    if @run.route.steps_as_json.nil?
      @steps = @run.route.steps.select(:latitude, :longitude).order(:position).as_json
      # markers
      @steps.each_with_index do |step, index|
        if index == 0
          step[:marker_html] = render_to_string(partial: "shared/marker")
        else
          step[:marker_html] = render_to_string(partial: "shared/markerarrive")
        end
      end
    else
      @steps = JSON.parse(@run.route.steps_as_json)
    end
  end

  def end_run
    @run = Run.find(params[:id])
    @run.ending_time = Time.now
    @run.save
    # redirect_to edit_run_path(@run)
    redirect_to summary_path(@run)
  end

  def summary
    @run = Run.find(params[:id])
    @route = @run.route
    @bookmark = Bookmark.find_by(user: current_user, route: @run.route) || Bookmark.new
  end

  def update
  end
end

app/views/runs/edit.html.erb
<h1>Your route has finished!</h1>
<h2>Summary</h2>
<p>Distance : </p>
<p>Total time : <%= Time.at(@run.ending_time - @run.starting_time).utc.strftime("%H:%M:%S") %></p>
<p>Pace : km</p>
<p>Upload a picture :</p>
<%= simple_form_for @bookmark do |f| %>
  <%= f.input :photos, as: :file, input_html: { class: "custom-form-input" } %>
  <%= f.submit "Favorite the Route" %>
<% end %>
 <%# <%= link_to "Favorite the Route", bookmarks_path  %>

app/views/runs/running.html.erb
<h1><%= @run.route.name %></h1>
<div class="gif">
<img src="https://res.cloudinary.com/dlmjemn37/image/upload/v1733322268/running-gif_upkibk.gif" alt="Running GIF" width="342" height="550">
</div>

<div data-controller="modal">
  <%= link_to 'Stop run',  end_run_path(@run), data: {
    turbo_method: :patch,
    turbo_frame: :summary_modal,
    action: "click->modal#display"
    }, class: 'btn btn-running' %>

  <div id="summary-modal-content" class="d-none" data-modal-target="modal">
    <%= turbo_frame_tag :summary_modal do %>
    <% end %>
  </div>

  <div id="summary-modal-backdrop" class="d-none" data-modal-target="modal">
  </div>
</div>

app/views/runs/show.html.erb
<div style="width: 100%; height: 500px;"
  data-controller="map"
  data-map-markers-value="<%= @steps.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <%= link_to 'New Route', new_route_path, class: 'btn btn-flat my-4' %>


  <h1 class="my-2"><%= @run.route.name %></h1>
  <p><strong>Description:</strong> <%= @run.route.description %></p>
  <p><strong>Distance:</strong> <%= @run.route.distance %> km</p>
  <p><strong>Comments:</strong> <%= @bookmark.comment %></p>


  <div id="carouselExample" class="carousel slide">
    <div class="carousel-inner">
      <% @bookmark.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>" >
        <%= cl_image_tag photo.key, class: "d-block w-100" %>
      </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/runs/summary.html.erb
<div class="container">
  <%= turbo_frame_tag :summary_modal, target: "_top" do %>

  <div class="row justify-content-center">
    <div class="col-lg-3 my-6">
      <div class="form-inputs-new">

  <div class="modal-content-title">
    <h1>Your route has finished!</h1>
    <button type="button" class="btn-close" aria-label="Close" data-action="modal#hide"></button>
  </div>

<!--summary data are hardcoded-->
<div data-controller="confetti">
    <h3>Summary</h3>
  <div class="inline-p">
    <div class="grid-container">
      <div class="distance">
        <div>Distance</div>
        <div><%= ((Time.at(@run.ending_time - @run.starting_time)).to_i * ( 8 / 3600.0)).round(2) %> km</div>
      </div>
      <div class="time">
        <div>Total time</div>
        <div><%= Time.at(@run.ending_time - @run.starting_time).utc.strftime("%H:%M:%S") %></div>
      </div>
      <div class="pace">
        <div>Pace</div>
        <div>8 km/h</div>
    </div>
  </div>
</div>

  <%= simple_form_for [ @run, @bookmark ], html: { multipart: true } do |f| %>
    <h4 id="comment-heading">Comments</h4>

    <%= f.input :comment, label: false, placeholder: "How do you feel?", as: :text, input_html: { rows: "10" }, input_html: { class: "custom-form-input" } %>

    <h4>Upload image</h4>
    <div class="upload-container">
      <label class="upload-box" for="upload-photo">
      <%= f.input :photos, label: false, as: :file, input_html: { id: "upload-photo", multiple: true, class: "hidden-file-input", accept: "image/*" } %>
      <img id="image-preview" alt="Preview">
      <span class="icon"><i class="fa-solid fa-camera-retro"></i></span>
      </label>
    </div>
    <%= f.button :submit, "Favorite this route", class: "btn btn-ghost btn-wide", id:"favorite-button", data: { turbo_frame: "_top" } %>
    <%= link_to "Finish", routes_path, class: "btn btn-flat-sum btn-wide", data: { turbo_frame: "_top" } %>
  <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>