config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "routes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :routes, only: %i[index new create show results] do
    resources :runs, only: %i[create] do
    get '/running', to: 'runs#running', as: :running
    end
  end

  get '/results', to: 'routes#results', as: :results
  patch '/end_run/:id', to: 'runs#end_run', as: :end_run
  resources :runs, only: %i[edit update show] do
    get '/running', to: 'runs#running', as: :running
    resources :bookmarks, only: %i[create update]
  end
  get "style", to: "pages#style"
  get "runs/:id/summary", to: "runs#summary", as: :summary

  resources :bookmarks, only: %i[index]
end

app/models/route.rb
class Route < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :runs
  has_many :steps
  has_many :bookmarks
end

app/controllers/routes_controller.rb
require "open-uri"

class RoutesController < ApplicationController
  require 'open-uri'

  def index
    @routes = Route.all
    @array = []
  end

  def new
    @route = Route.new
  end

  def show
    @route = Route.find(params[:id])
    if request.referer.split("/").last == "new"
      @start_address = I18n.transliterate(@route.start_address)
      @end_address = I18n.transliterate(@route.end_address)
      json_start = URI.parse("https://nominatim.openstreetmap.org/search.php?q=#{@start_address}&format=jsonv2").read
      JSON.parse(json_start)
      @start_lat = JSON.parse(json_start)[0]["lat"]
      @start_long = JSON.parse(json_start)[0]["lon"]

      json_end = URI.parse("https://nominatim.openstreetmap.org/search.php?q=#{@end_address}&format=jsonv2").read
      JSON.parse(json_end)
      @end_lat = JSON.parse(json_end)[0]["lat"]
      @end_long = JSON.parse(json_end)[0]["lon"]
      @distance = @route.distance

      client = OpenAI::Client.new
      chatgpt_response = client.chat(parameters: {
        model: "gpt-4o-mini",
        messages: [{ role: "user", content:
        "I am in Berlin Germany and I want to go for a run. I will start at #{@start_lat}, #{@start_long}
        and end at #{@end_lat}, #{@end_long}.
        The run should be approximately #{@distance}. Can you give me 5 waypoints (including the start and end points)
        with latitude and longitude that form a logical, connected route?
        Each point should be roughly equally spaced and follow real-world paths or streets.
        Please ensure the start and end points match the addresses provided.

        The response format should strictly be valid JSON text like this:

         [
            { \"latitude\": LATITUDE_VALUE, \"longitude\": LONGITUDE_VALUE },
            { \"latitude\": LATITUDE_VALUE, \"longitude\": LONGITUDE_VALUE },
            ...
          ]

        Do not add any comments, extra text or ``` in your response. Thank you!" }]
        })
      # @steps = eval(chatgpt_response["choices"][0]["message"]["content"].gsub("\n", "").gsub(" ", ""))


      @json = chatgpt_response["choices"][0]["message"]["content"]
      @steps = JSON.parse(@json)

      @steps.each_with_index do |step, index|
        if index == 0
          step[:marker_html] = render_to_string(partial: "shared/marker")
        else
          step[:marker_html] = render_to_string(partial: "shared/markerarrive")
        end
      end
      @route.steps_as_json = @steps.to_json

      client_name = OpenAI::Client.new
      chatgpt_response_name = client_name.chat(parameters: {
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: "
            I am going on a run.
            Can you please generate a nice name made with 3 words for my run mentionning the name of the neighbourhood in Berlin
            (Mitte, Kreuzberg, Neukoelln etc) but not the name of the street of #{@start_address} or #{@end_address}?
            Give me only the name of the run, without any of your own answer like 'Here is a nice name for...'.
            thank you!"
            }]
          })
      @route.name = chatgpt_response_name["choices"][0]["message"]["content"]
      client_description = OpenAI::Client.new
      chatgpt_response_description = client_description.chat(parameters: {
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: "
            I am going on a run.
            Can you please generate a very simple description for my run made with 1 sentence made with maximum 7 words,
            focusing on the neighbourhood (Mitte, Kreuzberg, Neukoelln etc) of #{@start_address} or #{@end_address}?
            Give me only the description of the run, without any of your own answer like 'Here is a nice name for...'.
            thank you!"
            }]
          })
      @route.description = chatgpt_response_description["choices"][0]["message"]["content"]
    else
      @steps = @route.steps.select(:latitude, :longitude).order(:position).as_json
      @steps.each_with_index do |step, index|
        if index == 0
          step[:marker_html] = render_to_string(partial: "shared/marker")
        else
          step[:marker_html] = render_to_string(partial: "shared/markerarrive")
        end
      end
    end
    @route.save
  @route.distance = fake_distance(@route.distance)
  @route.save


    @url = "https://api.openweathermap.org/data/2.5/weather?lat=52.52&lon=13.40&appid=93fad4ed2d411554730316c443c0e0df"
    @json = URI.parse(@url).read
    @data = JSON.parse(@json)
    @temperature = @data['main']['temp']
    @degree = @temperature.to_f - 273.15
    @weather = @data['weather'][0]['main']



    tips_description = OpenAI::Client.new
    chatgpt_response_tips = tips_description.chat(parameters: {
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: "
         I am going on a run.
          Can you please generate four nice tips for runners in Berlin on what they should wear depending on the weather today.
          The tips should be only 1 sentence with maximum 5 words and emojis as index and dont use any number as index please.
          Every tip should be on a different paragraph.
          The temperature is #{@degree} degrees today. Please don't add any comments or extra text from you.
          thank you!"
           }]
        })

        #@tips = chatgpt_response_tips["choices"][0]["message"]["content"].gsub("\n", " ").split(/(?=\d+\.\s)/).map(&:strip)
        @tips = chatgpt_response_tips["choices"][0]["message"]["content"].split("\n\n").map(&:strip)
  end


  def create
      @route = Route.new(route_params)
      @route.user = current_user
      @route.save
      redirect_to route_path(@route)
  end

  private

  def fake_distance(selected_distance)
    case selected_distance
    when '5 - 10km'
      rand(5..10)
    when '10 - 15km'
      rand(10..15)
    when '15 - 20km'
      rand(15..20)
    when '20 - 25 km'
      rand(20..25)
    else
      rand(5..25)
    end
  end

  def route_params
    params.require(:route).permit(:start_address, :end_address, :distance)
  end

  def results
    @routes = Route.order("RESULT()").first
  end
end

app/views/routes/index.html.erb
<div style="position: relative; width: 100%; height: 500px;">
  <div style="width: 100%; height: 100%;"
    data-controller="map"
    data-map-markers-value="<%= @array %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <!-- button positioned at the bottom -->
  <%= link_to 'New Route', new_route_path, class: 'btn btn-flat-newroute', style: 'position: absolute; bottom: 20px; left: 20%; transform: translateX(-9%); z-index: 20;' %>
</div>

<h1 class="my-3">Suggestions</h1>
<div class="cards_container">
  <% @routes.each do |route| %>
      <div class="card-run">
        <% if route.photo.attached? %>
        <%= cl_image_tag route.photo.key, width: 124, height: 124, crop: :fill, class: "image-card" %>
          <% else %>
        <%= image_tag "map.png",  width: 124, crop: :fill, class: "image-card" %>
          <% end %>
        <div class="card-run-infos">
          <h2><%= link_to route.name, route_path(route) %></h2>
          <div class="card-text-icon">
            <i class="fa-solid fa-person-running"></i>
            <p><strong>Distance:</strong> <%= route.distance %> km</p>
          </div>
          <p><%= route.description %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/routes/new.html.erb
<div class="container" data-controller="loading-animation">
  <div class="row justify-content-center">
    <div class="col-lg-3 my-6">
      <div class="form-inputs">
        <h2>Workout of the day</h2>
        <%= simple_form_for(@route) do |f| %>
        <%= f.input :start_address,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV['MAPBOX_API_KEY']},
                          class: "first-autocomplete"} %>
        <%= f.input :end_address,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV['MAPBOX_API_KEY']}} %>
        <%= f.input :distance, collection: ['5 - 10km', '10 - 15km', '15 - 20km', '20 - 25 km'],
     prompt: 'Select distance', input_html: { class: 'form-control' }, input_html: { class: "custom-form-input" } %>
        <%= f.submit class: "btn btn-flat btn-wide", id:"submit-button", data: {action: "click->loading-animation#display"} %>
        <% end %>
        <div><%= render "shared/loading" %></div>
      </div>
    </div>
  </div>
</div>

app/views/routes/results.html.erb
<h1>Your results</h1>
<% if @route %>
  <p><strong>Name:</strong> <%= @route.name %></p>
  <p><strong>Distance:</strong> <%= @route.distance %> miles</p>
  <p><strong>Location:</strong> <%= @route.location %></p>
  <p><strong>Difficulty:</strong> <%= @route.difficulty_level %></p>
<% else %>
  <p>No routes available.</p>
<% end %>
<a href="<%= routes_path %>">Show Another Random Route</a>

app/views/routes/show.html.erb
<div style="width: 100%; height: 500px;"
  data-controller="map"
  data-map-markers-value="<%= @steps.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<div>
  <%= link_to 'New Route', new_route_path, class: 'btn btn-flat my-4' %>
  <%= link_to route_path(@route), class: 'btn btn-ghost btn-ghost-refresh' do %>
  <i class="fa-solid fa-rotate-right"></i> Refresh
  <% end %>
</div>

<h1 class="my-2"><%= @route.name %></h1>
<div class="weather">
  <div class="align-itens">
    <% if @weather == "Clear" %>
    <span><i class="fa-solid fa-sun"></i></span>
    <% elsif  @weather == "Clouds" %>
    <span><i class="fa-solid fa-cloud"></i></span><% elsif @weather =="Rain" %>
    <span><i class="fa-solid fa-cloud-rain"></i></span>
    <% elsif  @weather == "Thunderstorm" %>
    <span><i class="fa-solid fa-cloud-bolt"></i></span>
    <% elsif @weather == "Snow" %>
    <span><i class="fa-solid fa-snowflake"></i></span>
    <% else %>
    <span><i class="fa-solid fa-cloud-sun"></i></span>
    <% end %>
    <span style="margin-right: 15px;"><%= @degree.round(0) %>°C</span>
  </div>
  <div class="align-itens">
    <span><i class="fa-solid fa-person-running"></i>
    <%= @route.distance %> km</span>
  </div>
</div>


<p><%= @route.description %></p>

<h2>Tips:</h2>

<% if @tips.present? %>
  <ul style="list-style-type: none" class="tips-list">
    <% @tips.each do |tip| %>
      <li><%= tip.strip %></li>
    <% end %>
  </ul>
<% end %>


<%= link_to 'Start',  route_runs_path(@route), data: { turbo_method: :post}, class: 'btn btn-flat btn-wide-wide {
  width: 100%
}' %>